[package]
name = "sat"
version = "0.0.0"
authors = ["Michael Walker <mike@barrucadu.co.uk>"]
edition = "2018"

[profile.test]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
